.PHONY: clean All

All:
	@echo "----------Building project:[ Pong - Debug ]----------"
	@cd "Pong" && "$(MAKE)" -f  "Pong.mk" && "$(MAKE)" -f  "Pong.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Pong - Debug ]----------"
	@cd "Pong" && "$(MAKE)" -f  "Pong.mk" clean
